[package]
name = "sensorgardenyew" 
version = "0.1.0" 
edition = "2021"

[dependencies]
yew = {version="0.20.0", features=["csr"]}
yew-router = "0.17"
trunk = "0.15.0"
serde_json = "1.0.96"
gloo-net = "0.2.6"
serde = { version = "1.0", features = ["derive"] }
wasm-bindgen-futures = "0.4"
