name: Build and Deploy Backend Services
on: 
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Test Go Build 
      run: go test -v ./...
      working-directory: ./backend

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DG_ACCESS_TOKEN }}

    - name: Doctl Register
      run: doctl registry login

    - name: Build and Push Dockerimage
      uses: docker/build-push-action@v2
      with: 
        file: ./backend/DockerFile
        push: true
        tags : registry.digitalocean.com/cooper-cluster-container-registry/com.cooperkyle.sensorgardenbackend

